### ISSUE TITLE
Container Registry Needed

### ISSUE THREAD

**Issue by brianwyka** [Optum/sourcehawk#61]
Need a container registry within Optum Github packages in order to push builder `docker` images.
https://github.com/orgs/Optum/packages

Github Docs:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by brianwyka** [comment]
@amyschoen, can you assist with this?

**Comment by amyschoen** [comment]
I'll take a look tomorrow @brianwyka

**Comment by brianwyka** [comment]
Thanks so much @amyschoen.

**Comment by brianwyka** [comment]
@amyschoen, I think I have confirmed that all I need is 2 secrets.  A username and token to push to the container registry, as outlined here:
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry

**Comment by amyschoen** [comment]
I think these shared secrets might work for you:

GIT_COMMITTER_TOKEN
GIT_USERNAME

**Comment by brianwyka** [comment]
I tried those.  Didn't have sufficient perms mentioned in documentation linked above.

**Comment by amyschoen** [comment]
That's what I get for not actually reading the documentation.  I'll take a closer look at what's needed.

**Comment by brianwyka** [comment]
Here are the relevant logs @amyschoen :
```
Successfully built c65c43891256
Successfully tagged ghcr.io/optum/ci/rpmbuild:fedora35
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Login Succeeded
...
denied: permission_denied: The token provided does not match expected scopes.
Error: Process completed with exit code 1.
```

**Comment by brianwyka** [comment]
Any update here @amyschoen ?

**Comment by amyschoen** [comment]
Sorry.  Took the last couple weeks of the year off.  I'll get you squared away in the next couple days.

**Comment by brianwyka** [comment]
Thanks @amyschoen !

**Comment by amyschoen** [comment]
I just created a new token and mapped it to GITHUB_PACKAGE_TOKEN.  Let me know if that works for you.

**Comment by brianwyka** [comment]
@amyschoen, I don't have access to this secret.  It's not showing up in the list of available ones in Github secrets UI for this repo.

**Comment by amyschoen** [comment]
I missed this banner when I added it yesterday.  Saw when I tried again this morning.

> Failed to add secret. Secret names must not start with GITHUB_.

It looks like it stuck when I named it GIT_PACKAGE_TOKEN.  Give that a try.

**Comment by brianwyka** [comment]
Success!  Thanks @amyschoen !

**Comment by amyschoen** [comment]
Awesome.  Glad it's working.  Let me know if you need any more help.

**Comment by brianwyka** [comment]
@amyschoen, seems like one more step is needed.  I successfully published the images to container registry.  However, I cannot pull them currently without authenticating.  Is it possible to allow public access to the images?

**Comment by amyschoen** [comment]
There shouldn't be anything restricting making packages public.  Try going into your package settings and changing the visibility.

**Comment by brianwyka** [comment]
The packages have been published.  I can't see them at all in Github UI.

**Comment by amyschoen** [comment]
You can't see this?

![Screen Shot 2022-01-07 at 11 06 17 AM](https://user-images.githubusercontent.com/7476114/148580096-7385b712-94e9-4c53-b996-a9b8982c1cd5.png)

In any case, I tweaked the permissions to allow org members to publish public packages.  Since this entire org is devoted to OSS, I see no reason why any of our packages should be private.

**Comment by amyschoen** [comment]
Also, we've had enough back and forth that it might just make sense to put a working session on the calendar for next week.

**Comment by brianwyka** [comment]
No, I can't see those packages at all.

**Comment by amyschoen** [comment]
Throw a half hour on my calendar and we can work through it.

**Comment by brianwyka** [comment]
How do I do that?  I'm not at Optum anymore.

**Comment by amyschoen** [comment]
I forgot about that.  That also explains why you can't see the artifacts.  I might need to fix the permissions on this one myself.  Can you adjust the package names so they're more in line with the other public packages and reflect that they're for sourcehawk?

**Comment by brianwyka** [comment]
I kept `sourcehawk` out the names since they are generic and can be used for other `ci` purposes.

**Comment by amyschoen** [comment]
Gotcha.  Then the names work.  I'll ping you once I think I fixed the package permissions so you can verify.

**Comment by brianwyka** [comment]
Great, thanks @amyschoen !

**Comment by amyschoen** [comment]
The two packages should be public now.

**Comment by ctoestreich** [comment]
@amyschoen, @brianwyka and I have both left optum fyi. So if you want to reach us you should use our email addresses attached to our public GitHub, LinkedIn or on here.

**Comment by brianwyka** [comment]
Thanks @amyschoen!  And yes, thanks @ctoestreich!

**Comment by amyschoen** [comment]
You're welcome @brianwyka 

Good to know @ctoestreich.  Is there anyone here who can take over for you as admin?  I'll keep you on the project, but we want to make sure we have our admins on the repos be an employee.

**Comment by brianwyka** [comment]
I would nominate Devin Houde if he accepts 🦇

**Comment by amyschoen** [comment]
I need to meet with Devin this week.  I'll ask him.

**Comment by amyschoen** [comment]
@brianwyka @ctoestreich 

@PseudoCoding agreed to take over as admin.  I've updated permissions on all the sourcehawk projects.

**Comment by brianwyka** [comment]
Thanks @PseudoCoding !
